service GoogleClient et youtube API opérationnel
WildCodeSchool-2024-02/rem-php-p3-origins-digital pull request #9
Opened 2024-06-20 09:30 UTC by Julio-Compressor

**POUR CETTE PR IL FAUT :**

- composer require google/apiclient:~2.0
- mettre absolument le client_secret.json qui se trouve dans discord projet dans /config/ :

![image](https://github.com/WildCodeSchool-2024-02/rem-php-p3-origins-digital/assets/156215224/7d169725-c128-4843-a214-8d678305ba03)

Et vérifier dans services.yaml : 
![image](https://github.com/WildCodeSchool-2024-02/rem-php-p3-origins-digital/assets/156215224/7a5325c0-89c5-47a2-a3e4-d8a4d64b1191)

2024-06-20 09:36 UTC, AliTraore approved these changes

2024-06-20 09:37 UTC, MatthWCS approved these changes
good

2024-06-21 06:33 UTC, vravanel requested changes

2024-06-21 06:33 UTC, vravanel commented on docker-compose.yml
> +###> doctrine/doctrine-bundle ###
Pourquoi ce fichier a été modifié ?

2024-06-25 14:33 UTC, Julio-Compressor commented on docker-compose.yml
> +###> doctrine/doctrine-bundle ###
aucune idée je n'y ai pas touché pourtant :/

2024-06-26 12:34 UTC, vravanel approved these changes

2024-06-26 12:34 UTC, vravanel commented on docker-compose.yml
> +###> doctrine/doctrine-bundle ###
Enlève tout ce qui est par rapport à PostgresSql et ça sera good 👍

2024-06-26 12:34 UTC, merged